// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ddd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FffClient is the client API for Fff service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FffClient interface {
	SayHello456(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type fffClient struct {
	cc grpc.ClientConnInterface
}

func NewFffClient(cc grpc.ClientConnInterface) FffClient {
	return &fffClient{cc}
}

func (c *fffClient) SayHello456(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/ccc.ddd.fff/SayHello456", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FffServer is the server API for Fff service.
// All implementations must embed UnimplementedFffServer
// for forward compatibility
type FffServer interface {
	SayHello456(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedFffServer()
}

// UnimplementedFffServer must be embedded to have forward compatible implementations.
type UnimplementedFffServer struct {
}

func (UnimplementedFffServer) SayHello456(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello456 not implemented")
}
func (UnimplementedFffServer) mustEmbedUnimplementedFffServer() {}

// UnsafeFffServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FffServer will
// result in compilation errors.
type UnsafeFffServer interface {
	mustEmbedUnimplementedFffServer()
}

func RegisterFffServer(s grpc.ServiceRegistrar, srv FffServer) {
	s.RegisterService(&Fff_ServiceDesc, srv)
}

func _Fff_SayHello456_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FffServer).SayHello456(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ccc.ddd.fff/SayHello456",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FffServer).SayHello456(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fff_ServiceDesc is the grpc.ServiceDesc for Fff service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fff_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ccc.ddd.fff",
	HandlerType: (*FffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello456",
			Handler:    _Fff_SayHello456_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fff.proto",
}
